9# Create page of the register decimate
MFE-guys/Tither-UI pull request #12
Opened 2023-08-05 19:55 UTC by josileudo

### Description

- Create a dropdown menu with routes;
- Create a form to save decimate;
- Config `routes` file;

### Have a style change?

![Kapture 2023-08-05 at 16 51 31](https://github.com/MFE-guys/Tither-UI/assets/48743781/4909ebde-d141-4e82-8909-d937f330bdc9)

### PR Checklist

#### Please check if your PR fulfills the following requirements:

Add a new route to register a decimate.

#### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

Closes #9 

- [ ] Yes
- [x] No

2023-08-06 16:01 UTC, luiz258 commented on src/app/pages/Register/index.ts
> +    RouterModule,
I think I could create a Shared Module to import these basic Modules, I'm seeing several repeats and the code is getting long

2023-08-06 16:05 UTC, luiz258 requested changes

2023-08-06 16:05 UTC, luiz258 commented on src/main.ts
> +    provideState(themeFeature),
so podemos declarar so um estado dentro do provideState?

provideState(createMemberFeature, messageFeature, themeFeature),
É viavel fazer dessa forma acima?

2023-08-06 16:05 UTC, luiz258 commented on src/styles.scss
> +  // transition: all 0.2s;
remove comment

2023-08-07 12:09 UTC, josileudo commented on src/app/pages/Register/index.ts
> +    RouterModule,
This is a big suggestion, but this will escape the standalone architecture

2023-08-07 12:25 UTC, josileudo commented on src/main.ts
> +    provideState(themeFeature),
No, this way
 ```js
provideState(createMemberFeature, messageFeature, themeFeature)
```
 I can create a file, for example, a index.ts, and called a function and input this 
 
 ```js
 export function provideRegisterFeature(): EnvironmentProviders {
  return makeEnvironmentProviders([
    provideState(createMemberFeature),
    provideState(messageFeature),
    provideState(themeFeature),
  ]);
}
 ```
 
 So, importing here 
 ```js
 
bootstrapApplication(AppComponent, {
  providers: [
    importProvidersFrom(
      BrowserModule,
      BrowserAnimationsModule,
      HttpClientModule
    ),
    provideStore(),
    provideRegisterFeature(),
    provideRouter(routes),
    provideStoreDevtools(),
    provideEffects(CreateMemberEffect),
    { provide: LOCALE_ID, useValue: 'pt' },
    { provide: DEFAULT_CURRENCY_CODE, useValue: 'BRL' }
  ]
});
 ```

2023-08-07 12:32 UTC, josileudo commented on src/styles.scss
> +  // transition: all 0.2s;
fixed

2023-08-30 21:37 UTC, merged